apiVersion: v1
kind: PersistentVolume
metadata:
  name: opstree-vol
  labels:
    type: local
spec:
  storageClassName: standard   #gcp storage classname
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt"
