apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opstree-vol-claim
spec:
  storageClassName: standard
  selector:
    matchLabels:
        type: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
